title: Buy accessories for your beautiful bike | Shop4Moto
tagline: Toolkit for launching your new project. Start by forking on github
description: Make a launch site for your new webpage. Add an email list, HTTPS, free webhosting
url: https://shop4moto.com

logo: /images/logo.png
backgroundImage: /images/background-doodles.png

mailchimpURI:
mailchimpAntiSpamCode:

showPrivacyPolicy: false

socialMediaImage: /images/logo.png
twitter:
facebook:
instagram:

forkMeOnGithub: false #se this false to remove fork me on github ribbon
